version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build: .
    env_file:
      - ./.env
    depends_on:
      - mongo #starts mongo service first and then goes to node, use --no-deps to start only node
      - redis
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=krishna
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongo-db:
